import { db } from "@workspace/db";
import { governmentOpportunitiesTable } from "@workspace/db";

async function seedOpportunities() {
  console.log("Seeding government opportunities...");

  await db.delete(governmentOpportunitiesTable);

  await db.insert(governmentOpportunitiesTable).values([
    {
      title: "ADP Fertilizer Subsidy Programme 2026",
      description: "Kano State Agricultural Development Programme is offering subsidized NPK and Urea fertilizers to registered smallholder farmers for the 2026 wet season. Apply before the deadline to receive up to 50% subsidy on 5 bags of fertilizer.",
      provider: "Kano State ADP",
      providerType: "government",
      opportunityType: "subsidy",
      eligibleFarmTypes: ["crop", "mixed"],
      targetStates: ["Kano", "Kaduna", "Katsina"],
      amountNgn: 75000,
      amountDescription: "Up to ₦75,000 in fertilizer subsidy",
      deadline: new Date("2026-07-31"),
      applicationUrl: "https://kanoadp.gov.ng/fertilizer-subsidy",
      contactPhone: "064-311-200",
      contactEmail: "fertilizer@kanoadp.gov.ng",
      requirements: [
        "Valid National ID or NIN",
        "Farm registration with ADP",
        "Farm must be minimum 0.5 hectares",
        "Active bank account (BVN required)",
        "Proof of residence in eligible LGA",
      ],
      benefits: [
        "50% subsidy on NPK 15-15-15 fertilizer",
        "50% subsidy on Urea fertilizer",
        "Up to 5 bags at subsidized rate",
        "Free soil testing included",
      ],
      isActive: true,
      isFeatured: true,
    },
    {
      title: "Federal Government Anchor Borrowers Programme",
      description: "The Central Bank of Nigeria's Anchor Borrowers Programme provides single-digit interest rate loans to smallholder farmers for crop production. Loans disbursed directly to farmers' bank accounts. Repayment starts after harvest.",
      provider: "Central Bank of Nigeria / CBN",
      providerType: "government",
      opportunityType: "grant",
      eligibleFarmTypes: ["crop", "livestock", "mixed"],
      targetStates: ["All States"],
      amountNgn: 500000,
      amountDescription: "Loans from ₦100,000 to ₦500,000",
      deadline: new Date("2026-09-30"),
      applicationUrl: "https://anchorborrowers.cbn.gov.ng",
      contactPhone: "0700-CBN-HELP",
      contactEmail: "anchorborrowers@cbn.gov.ng",
      requirements: [
        "Registered with any Agric cooperative",
        "BVN and valid bank account",
        "Farm must be minimum 1 hectare",
        "Crop insurance required",
        "Attend one-day training",
      ],
      benefits: [
        "Single digit interest rate (9% per annum)",
        "No collateral required",
        "Repayment after harvest season",
        "Free crop insurance coverage",
        "Access to certified seeds and inputs",
      ],
      isActive: true,
      isFeatured: true,
    },
    {
      title: "FAO Emergency Livestock Vaccination Campaign",
      description: "The Food and Agriculture Organization, in partnership with the Federal Ministry of Agriculture, is conducting free vaccination campaigns for smallholder livestock farmers. Vaccines available for PPR, FMD, CCPP, and Newcastle disease.",
      provider: "FAO Nigeria / Federal MARD",
      providerType: "ngo",
      opportunityType: "subsidy",
      eligibleFarmTypes: ["livestock", "mixed"],
      targetStates: ["Kano", "Sokoto", "Zamfara", "Kebbi", "Katsina"],
      amountNgn: null,
      amountDescription: "Free vaccines and veterinary services",
      deadline: new Date("2026-08-15"),
      applicationUrl: null,
      contactPhone: "0800-FAO-AGRIC",
      contactEmail: "livestock-health@fao-nigeria.org",
      requirements: [
        "Minimum 5 animals to qualify",
        "Registration at local veterinary office",
        "Animals must be accessible at farm",
      ],
      benefits: [
        "Free PPR vaccine for goats and sheep",
        "Free FMD vaccine for cattle",
        "Free Newcastle vaccine for poultry",
        "Free veterinary health check",
        "Vaccination certificate issued",
      ],
      isActive: true,
      isFeatured: false,
    },
    {
      title: "NIRSAL Agribusiness Loan Guarantee",
      description: "Nigeria Incentive-Based Risk Sharing System for Agricultural Lending (NIRSAL) provides credit guarantees of up to 75% for agribusiness loans, enabling farmers to access commercial bank credit at reduced interest rates.",
      provider: "NIRSAL PLC",
      providerType: "government",
      opportunityType: "grant",
      eligibleFarmTypes: ["crop", "livestock", "mixed", "agribusiness"],
      targetStates: ["All States"],
      amountNgn: 5000000,
      amountDescription: "Loan guarantee up to ₦5 million",
      deadline: null,
      applicationUrl: "https://nirsal.com/loans",
      contactPhone: "0700-NIRSAL-1",
      contactEmail: "info@nirsal.com",
      requirements: [
        "Registered business or cooperative",
        "CAC registration certificate",
        "6-month bank statement",
        "Farm business plan",
        "Acceptable collateral or cooperative backing",
      ],
      benefits: [
        "75% credit guarantee to commercial banks",
        "Access to ₦500,000 to ₦5,000,000",
        "Interest rate cap of 9% per annum",
        "Technical assistance included",
        "Insurance coverage available",
      ],
      isActive: true,
      isFeatured: false,
    },
    {
      title: "IFAD Rural Finance Programme",
      description: "The International Fund for Agricultural Development is offering grants to smallholder farmers to improve access to financial services. Includes financial literacy training, savings group formation, and direct cash grants for farm improvements.",
      provider: "IFAD Nigeria",
      providerType: "ngo",
      opportunityType: "grant",
      eligibleFarmTypes: ["crop", "livestock", "mixed"],
      targetStates: ["Kano", "Niger", "Kebbi", "Sokoto"],
      amountNgn: 200000,
      amountDescription: "Direct grants of ₦50,000 to ₦200,000",
      deadline: new Date("2026-10-31"),
      applicationUrl: "https://ifad-nigeria.org/rural-finance",
      contactPhone: "09-461-8000",
      contactEmail: "grants@ifad-nigeria.org",
      requirements: [
        "Female farmers or female-led cooperatives prioritized",
        "Household income below ₦500,000 per year",
        "Minimum 2 years farming experience",
        "Attend 3-day financial literacy training",
      ],
      benefits: [
        "Direct cash grant (no repayment)",
        "Financial literacy training",
        "Savings group membership",
        "Mobile money account setup",
        "Follow-on technical support",
      ],
      isActive: true,
      isFeatured: false,
    },
    {
      title: "Kano State Youth in Agriculture Programme",
      description: "The Kano State Government is recruiting young farmers (18-35) to participate in a fully funded farm establishment scheme. Participants receive land allocation, equipment, seeds, and a monthly stipend for 12 months.",
      provider: "Kano State Ministry of Agriculture",
      providerType: "government",
      opportunityType: "training",
      eligibleFarmTypes: ["crop", "livestock", "mixed"],
      targetStates: ["Kano"],
      amountNgn: 720000,
      amountDescription: "₦60,000 monthly stipend × 12 months",
      deadline: new Date("2026-07-15"),
      applicationUrl: "https://kanoagric.gov.ng/youth-programme",
      contactPhone: "064-640-300",
      contactEmail: "youth@kanoagric.gov.ng",
      requirements: [
        "Age 18-35 years",
        "Kano State indigene",
        "Minimum SSCE/WAEC certificate",
        "Physically fit for farm work",
        "No current government employment",
      ],
      benefits: [
        "1 hectare of land allocated for 5 years",
        "Starter seed and input package",
        "Farm tools and equipment",
        "₦60,000 monthly stipend for 12 months",
        "Business skills training",
        "Market linkage support",
      ],
      isActive: true,
      isFeatured: true,
    },
    {
      title: "GIZ Green Innovation Centres Training",
      description: "The German International Cooperation Agency is offering free vocational training for farmers in improved agricultural practices, including precision farming, post-harvest management, and climate-smart agriculture techniques.",
      provider: "GIZ / German Government",
      providerType: "ngo",
      opportunityType: "training",
      eligibleFarmTypes: ["crop", "livestock", "mixed"],
      targetStates: ["Kano", "Kaduna", "Plateau"],
      amountNgn: null,
      amountDescription: "Free training (travel and accommodation covered)",
      deadline: new Date("2026-08-30"),
      applicationUrl: "https://giz-nigeria.org/green-innovation",
      contactPhone: "09-291-3000",
      contactEmail: "training@giz-nigeria.org",
      requirements: [
        "Active farmer with at least 0.5 hectare",
        "Commitment to attend full 5-day training",
        "Willingness to adopt improved practices",
        "Basic literacy in English or Hausa",
      ],
      benefits: [
        "5-day residential training",
        "Certificate of completion",
        "Travel and accommodation fully covered",
        "Starter pack of improved seeds",
        "Ongoing extension support",
        "Network of trained farmers",
      ],
      isActive: true,
      isFeatured: false,
    },
    {
      title: "USAID Feed the Future Equipment Grant",
      description: "USAID Feed the Future programme is awarding equipment grants to farmers willing to adopt climate-smart irrigation technologies. Solar-powered irrigation pumps available for eligible smallholder farmers.",
      provider: "USAID Feed the Future",
      providerType: "ngo",
      opportunityType: "equipment",
      eligibleFarmTypes: ["crop", "mixed"],
      targetStates: ["Kano", "Jigawa", "Katsina", "Sokoto"],
      amountNgn: 350000,
      amountDescription: "Solar pump valued at ₦350,000",
      deadline: new Date("2026-09-15"),
      applicationUrl: "https://feedthefuture.gov/nigeria-equipment",
      contactPhone: "09-461-4400",
      contactEmail: "equipment@fta-nigeria.org",
      requirements: [
        "Farm must have access to groundwater",
        "Minimum 2 hectares under irrigation",
        "Agree to USAID monitoring for 3 years",
        "Complete one-day installation training",
      ],
      benefits: [
        "Solar-powered irrigation pump (free)",
        "Installation and commissioning included",
        "12-month warranty and technical support",
        "Water management training",
        "Improved crop yield expected 40-60%",
      ],
      isActive: true,
      isFeatured: false,
    },
  ]);

  console.log("✅ Seeded 8 government opportunities");
  process.exit(0);
}

seedOpportunities().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
